---
- name: Deploy nginx on all nodes
  hosts: all
  roles:
    - common

- name: Deploy percona servers
  hosts: perconaservers
  roles:
    - perconaservers

- name: Deploy puppet server
  hosts: puppet
  roles:
    - puppetserver
