---

- name: Add Percona repository
  become: yes
  become_user: root
  apt: deb="https://repo.percona.com/apt/percona-release_0.1-6.xenial_all.deb"

- name: Update apt
  become: yes
  become_user: root
  apt: update_cache=yes

- name: Unstall Percona MySQL Server
  become: yes
  become_user: root
  action: apt pkg={{ item }} state=absent
  with_items:
    - percona-server-server-5.7
    - percona-server-client-5.7
    - percona-toolkit
    - percona-xtrabackup
    - python-mysqldb

# Example that prints the loopback address and gateway for each host
- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

#- name: Deploy index template
#  template:
#    src: index.j2
#    dest: /var/www/html/index.html
