---
- name: Deploy nginx on all nodes
  hosts: all
  roles:
    - common

- name: Deploy web servers
  hosts: webservers
  roles:
    - webservers

- name: Deploy keepalived
  hosts: nginx-lb
  roles:
  - nginx-lb
    
