---
- name: Installing sshpass
  apt: 
    name: sshpass
    state: present

- name: Installing locate search package
  apt:
    name:
    - locate
    state: present

- name: Installing Puppet and Ntp on Ubungu systems
  apt: 
    name: 
    - puppet
    - ntp
    state: present 
  when: ansible_os_family == "Debian"

- name: Deploy Motd to all systems
  template:
    src: motd.j2
    dest: /etc/motd
